{% set name = "junitparser" %}
{% set version = "2.8.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/junitparser-{{ version }}.tar.gz
  sha256: a8d4290ab9fb93f2015e0dbef61ef93b7ea110e99099087a453f55c8e1481adf

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0
  entry_points:
    - junitparser = junitparser.cli:main

requirements:
  host:
    - python >=3.6
    - pip
    # used in setup.py
    - future
  run:
    - python >=3.6
    - future

test:
  imports:
    - junitparser
  commands:
    - pip check
    - junitparser --help
  requires:
    - pip

about:
  home: https://github.com/weiwei/junitparser
  summary: Manipulates JUnit/xUnit Result XML files
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - mariusvniekerk
